title: py-building-gen
description: Generador paramétrico de scripts Dynamo para Revit 2027
author: Federico Ariel Casado
email: federicoarielcasado@gmail.com
url: "https://federicoarielcasado.github.io"
baseurl: "/py-building-gen"
lang: es
